name: Tutorial
version: '${version}'
main: me.expentled.tutorial.Tutorial
api-version: 1.19
authors: [ Expentled ]
description: A tutorial plugin for YouTube

commands:
  hello:
    description: A hello command
    aliases: [ test ]